# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'QuizApp Starter Kit All In One 1.0' do
pod 'SwiftyStoreKit'
pod 'Google-Mobile-Ads-SDK'
pod 'GoogleMobileAdsMediationAdColony'
pod 'GoogleMobileAdsMediationAppLovin'
pod 'GoogleMobileAdsMediationChartboost'
pod 'GoogleMobileAdsMediationFacebook'
pod 'GoogleMobileAdsMediationFyberMarketplace'
pod 'GoogleMobileAdsMediationIMobile'
pod 'GoogleMobileAdsMediationInMobi'
pod 'GoogleMobileAdsMediationMoPub'
pod 'GoogleMobileAdsMediationMyTarget'
pod 'GoogleMobileAdsMediationNend'
pod 'GoogleMobileAdsMediationUnity'
pod 'GoogleMobileAdsMediationVerizonMedia'
pod 'GoogleMobileAdsMediationVungle'
end


